plt.plot(x1_traj,y1_traj, label = 'Star 1')
plt.plot(x2_traj,y2_traj, label = 'Star 2')
plt.plot(x3_traj,y3_traj, label = 'Star 3')
plt.plot(xcom_traj,ycom_traj, label = 'center of mass')
plt.scatter(x = x1_traj[0] ,y = y1_traj[0], label = 'Star 1 intial position')
plt.scatter(x = x2_traj[0] ,y = y2_traj[0], label = 'Star 2 intial position')
plt.scatter(x = x3_traj[0] ,y = y3_traj[0], label = 'Star 3 intial position')
plt.title('3-body problem in lab frame', font = 'times new roman')
plt.xlabel('x',fontsize = 20, font = 'times new roman')
plt.ylabel('y',fontsize = 20, font = 'times new roman')
plt.tight_layout()
plt.legend()
#plt.savefig('3-body_problem_in_lab_frame.png', dpi = 1500)
plt.show()
